package br.edu.unifei.eco.tfg.gamification;

import br.edu.unifei.eco.tfg.gamification.view.*;
import static com.codename1.ui.CN.*;
import com.codename1.io.Log;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Image;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class App {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
    public void start(){
        List<Image> list = new ArrayList<>();
        for(int i=0;i<3;i++){
            try {
                list.add(Image.createImage("/img.png").scaled(75,75));
            } catch (IOException ex) {
            }
        }
        if(current != null){
            current.show();
            return;
        }
        try {
            current = new Home("Wu Liang Kuan",100,Image.createImage("/4houses.jpg"),list);
            //current = new Login();
//        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
//        final Label apple = new Label(theme.getImage("apple-icon.png"));
//        final Label android = new Label(theme.getImage("android-icon.png"));
//        final Label windows = new Label(theme.getImage("windows-icon.png")); 
//        Button getStarted = new Button("Let's Get Started!");
//        FontImage.setMaterialIcon(getStarted, FontImage.MATERIAL_LINK);
//        getStarted.setUIID("GetStarted");
//        hi.addComponent(BorderLayout.CENTER, 
//                LayeredLayout.encloseIn(
//                        BoxLayout.encloseY(
//                                new Label(theme.getImage("duke-no-logos.png")),
//                                getStarted
//                        ),
//                        FlowLayout.encloseRightMiddle(apple)
//                    )
//        );
//        
//        getStarted.addActionListener((e) -> {
//            execute("https://www.codenameone.com/developers.html");
//        });
//        
//        new UITimer(() -> {
//            if(apple.getParent() != null) {
//                apple.getParent().replace(apple, android, CommonTransitions.createFade(500));
//            } else {
//                if(android.getParent() != null) {
//                    android.getParent().replace(android, windows, CommonTransitions.createFade(500));
//                } else {
//                    windows.getParent().replace(windows, apple, CommonTransitions.createFade(500));
//                }                
//            }
//        }).schedule(2200, true, hi);
//        hi.show();
        } catch (IOException ex) {
            System.out.println("An IOException occurred!");
        }
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
